spring:
  application:
    name: kuro

  datasource:
    url: jdbc:sqlite:./data/library.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

resilience4j:
  circuitbreaker:
    configs:
      defaults:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-sate: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based